#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Install Specy tree-sitter parsers for Neovim
#
# Appends Specy configuration to init.lua (idempotent — skips if already present).
# Requires: Neovim 0.10+, parsers already built (run build.sh first).
#
# Usage: ./src/tree-sitters/install-nvim.sh [nvim-config-dir]
#   Default nvim-config-dir: ~/.config/nvim
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
NVIM_DIR="${1:-$HOME/.config/nvim}"
INIT_LUA="$NVIM_DIR/init.lua"

MARKER="-- [specy-tree-sitter]"

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------

# shellcheck source=./check-tree-sitter.sh
source "$SCRIPT_DIR/check-tree-sitter.sh"
check_tree_sitter_cli

# Check parsers are built
parser_ext="dylib"
[[ "$(uname)" == "Linux" ]] && parser_ext="so"

missing=0
for parser_dir in "$SCRIPT_DIR"/tree-sitter-specy-*; do
  name=$(basename "$parser_dir")
  # dylib name uses hyphens (e.g. specy-domain.dylib)
  lib_name="${name#tree-sitter-}"
  if [[ ! -f "$parser_dir/$lib_name.$parser_ext" ]]; then
    echo "ERROR: $name not built ($lib_name.$parser_ext not found)"
    echo "       Run ./src/tree-sitters/build.sh first."
    missing=1
  fi
done
[[ $missing -eq 1 ]] && exit 1

# Check init.lua exists or create it
if [[ ! -d "$NVIM_DIR" ]]; then
  mkdir -p "$NVIM_DIR"
  echo "Created $NVIM_DIR"
fi

if [[ ! -f "$INIT_LUA" ]]; then
  touch "$INIT_LUA"
  echo "Created $INIT_LUA"
fi

# Check idempotency
if grep -q "$MARKER" "$INIT_LUA" 2>/dev/null; then
  echo "Specy tree-sitter config already present in $INIT_LUA"
  echo "To reinstall, remove the $MARKER block first."
  exit 0
fi

# ---------------------------------------------------------------------------
# Generate the Lua config block
# ---------------------------------------------------------------------------

cat >> "$INIT_LUA" << LUAEOF

$MARKER
-- Specy tree-sitter integration (auto-generated by install-nvim.sh)
-- Remove this block (up to the next -- [/specy-tree-sitter]) to uninstall.
do
  local SPECY_ROOT = '$REPO_ROOT'
  local parser_ext = vim.fn.has('mac') == 1 and 'dylib' or 'so'

  local parsers = {
    {
      lang = 'specy_domain',
      lib  = 'specy-domain',
      dir  = SPECY_ROOT .. '/src/tree-sitters/tree-sitter-specy-domain',
      patterns = { ['.*%.domain'] = 'specy_domain' },
    },
    {
      lang = 'specy_prd',
      lib  = 'specy-prd',
      dir  = SPECY_ROOT .. '/src/tree-sitters/tree-sitter-specy-prd',
      patterns = { ['.*%.prd'] = 'specy_prd' },
    },
    {
      lang = 'specy_sysreq',
      lib  = 'specy-sysreq',
      dir  = SPECY_ROOT .. '/src/tree-sitters/tree-sitter-specy-sysreq',
      patterns = { ['.*%.sysreq'] = 'specy_sysreq' },
    },
  }

  for _, p in ipairs(parsers) do
    vim.filetype.add({ pattern = p.patterns })
    vim.treesitter.language.add(p.lang, {
      path = p.dir .. '/' .. p.lib .. '.' .. parser_ext,
    })
    vim.opt.runtimepath:append(p.dir)
  end

  vim.api.nvim_create_autocmd('FileType', {
    pattern = { 'specy_domain', 'specy_prd', 'specy_sysreq' },
    callback = function()
      vim.treesitter.start()
    end,
  })
end
-- [/specy-tree-sitter]
LUAEOF

echo "Specy tree-sitter config appended to $INIT_LUA"
echo ""
echo "Parsers registered:"
echo "  .domain  → specy_domain"
echo "  .prd     → specy_prd"
echo "  .sysreq  → specy_sysreq"
echo ""
echo "Open a .domain file in Neovim and run :InspectTree to verify."
