/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#ifdef _MSC_VER
#pragma optimize("", off)
#elif defined(__clang__)
#pragma clang optimize off
#elif defined(__GNUC__)
#pragma GCC optimize ("O0")
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 78
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_requirements = 1,
  anon_sym_scoped_DASHto = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_module = 5,
  anon_sym_prd_DASHsource = 6,
  anon_sym_COLON = 7,
  anon_sym_priority = 8,
  sym_requirement_id = 9,
  anon_sym_ubiquitous = 10,
  anon_sym_state_DASHdriven = 11,
  anon_sym_event_DASHdriven = 12,
  anon_sym_unwanted = 13,
  anon_sym_optional = 14,
  anon_sym_complex = 15,
  anon_sym_COLON_COLON = 16,
  anon_sym_must = 17,
  anon_sym_should = 18,
  anon_sym_could = 19,
  anon_sym_wont = 20,
  anon_sym_source = 21,
  anon_sym_depends_DASHon = 22,
  anon_sym_COMMA = 23,
  anon_sym_conflicts_DASHwith = 24,
  anon_sym_decomposed_DASHinto = 25,
  anon_sym_satisfied_DASHby = 26,
  anon_sym_implemented_DASHby = 27,
  anon_sym_structured_DASHby = 28,
  anon_sym_enforced_DASHby = 29,
  anon_sym_detected_DASHby = 30,
  anon_sym_quality_DASHconstrained_DASHby = 31,
  sym_satisfied_by_infrastructure = 32,
  anon_sym_DOT = 33,
  sym_string_literal = 34,
  sym_type_name = 35,
  sym_identifier = 36,
  sym_comment = 37,
  sym_source_file = 38,
  sym_requirement_set_def = 39,
  sym_module_block = 40,
  sym_prd_source_decl = 41,
  sym_requirement_def = 42,
  sym_ears_pattern = 43,
  sym_ears_statement = 44,
  sym_rationale = 45,
  sym_moscow_priority = 46,
  sym_source_decl = 47,
  sym_depends_on_decl = 48,
  sym_conflicts_with_decl = 49,
  sym_decomposed_into_block = 50,
  sym_satisfied_by_block = 51,
  sym_implemented_by_clause = 52,
  sym_structured_by_clause = 53,
  sym_enforced_by_clause = 54,
  sym_detected_by_clause = 55,
  sym_quality_constrained_by_clause = 56,
  sym_domain_ref = 57,
  aux_sym_source_file_repeat1 = 58,
  aux_sym_requirement_set_def_repeat1 = 59,
  aux_sym_module_block_repeat1 = 60,
  aux_sym_requirement_def_repeat1 = 61,
  aux_sym_requirement_def_repeat2 = 62,
  aux_sym_depends_on_decl_repeat1 = 63,
  aux_sym_decomposed_into_block_repeat1 = 64,
  aux_sym_satisfied_by_block_repeat1 = 65,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_requirements] = "requirements",
  [anon_sym_scoped_DASHto] = "scoped-to",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_module] = "module",
  [anon_sym_prd_DASHsource] = "prd-source",
  [anon_sym_COLON] = ":",
  [anon_sym_priority] = "priority",
  [sym_requirement_id] = "requirement_id",
  [anon_sym_ubiquitous] = "ubiquitous",
  [anon_sym_state_DASHdriven] = "state-driven",
  [anon_sym_event_DASHdriven] = "event-driven",
  [anon_sym_unwanted] = "unwanted",
  [anon_sym_optional] = "optional",
  [anon_sym_complex] = "complex",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_must] = "must",
  [anon_sym_should] = "should",
  [anon_sym_could] = "could",
  [anon_sym_wont] = "wont",
  [anon_sym_source] = "source",
  [anon_sym_depends_DASHon] = "depends-on",
  [anon_sym_COMMA] = ",",
  [anon_sym_conflicts_DASHwith] = "conflicts-with",
  [anon_sym_decomposed_DASHinto] = "decomposed-into",
  [anon_sym_satisfied_DASHby] = "satisfied-by",
  [anon_sym_implemented_DASHby] = "implemented-by",
  [anon_sym_structured_DASHby] = "structured-by",
  [anon_sym_enforced_DASHby] = "enforced-by",
  [anon_sym_detected_DASHby] = "detected-by",
  [anon_sym_quality_DASHconstrained_DASHby] = "quality-constrained-by",
  [sym_satisfied_by_infrastructure] = "satisfied_by_infrastructure",
  [anon_sym_DOT] = ".",
  [sym_string_literal] = "string_literal",
  [sym_type_name] = "type_name",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_requirement_set_def] = "requirement_set_def",
  [sym_module_block] = "module_block",
  [sym_prd_source_decl] = "prd_source_decl",
  [sym_requirement_def] = "requirement_def",
  [sym_ears_pattern] = "ears_pattern",
  [sym_ears_statement] = "ears_statement",
  [sym_rationale] = "rationale",
  [sym_moscow_priority] = "moscow_priority",
  [sym_source_decl] = "source_decl",
  [sym_depends_on_decl] = "depends_on_decl",
  [sym_conflicts_with_decl] = "conflicts_with_decl",
  [sym_decomposed_into_block] = "decomposed_into_block",
  [sym_satisfied_by_block] = "satisfied_by_block",
  [sym_implemented_by_clause] = "implemented_by_clause",
  [sym_structured_by_clause] = "structured_by_clause",
  [sym_enforced_by_clause] = "enforced_by_clause",
  [sym_detected_by_clause] = "detected_by_clause",
  [sym_quality_constrained_by_clause] = "quality_constrained_by_clause",
  [sym_domain_ref] = "domain_ref",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_requirement_set_def_repeat1] = "requirement_set_def_repeat1",
  [aux_sym_module_block_repeat1] = "module_block_repeat1",
  [aux_sym_requirement_def_repeat1] = "requirement_def_repeat1",
  [aux_sym_requirement_def_repeat2] = "requirement_def_repeat2",
  [aux_sym_depends_on_decl_repeat1] = "depends_on_decl_repeat1",
  [aux_sym_decomposed_into_block_repeat1] = "decomposed_into_block_repeat1",
  [aux_sym_satisfied_by_block_repeat1] = "satisfied_by_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_requirements] = anon_sym_requirements,
  [anon_sym_scoped_DASHto] = anon_sym_scoped_DASHto,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_prd_DASHsource] = anon_sym_prd_DASHsource,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_priority] = anon_sym_priority,
  [sym_requirement_id] = sym_requirement_id,
  [anon_sym_ubiquitous] = anon_sym_ubiquitous,
  [anon_sym_state_DASHdriven] = anon_sym_state_DASHdriven,
  [anon_sym_event_DASHdriven] = anon_sym_event_DASHdriven,
  [anon_sym_unwanted] = anon_sym_unwanted,
  [anon_sym_optional] = anon_sym_optional,
  [anon_sym_complex] = anon_sym_complex,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_must] = anon_sym_must,
  [anon_sym_should] = anon_sym_should,
  [anon_sym_could] = anon_sym_could,
  [anon_sym_wont] = anon_sym_wont,
  [anon_sym_source] = anon_sym_source,
  [anon_sym_depends_DASHon] = anon_sym_depends_DASHon,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_conflicts_DASHwith] = anon_sym_conflicts_DASHwith,
  [anon_sym_decomposed_DASHinto] = anon_sym_decomposed_DASHinto,
  [anon_sym_satisfied_DASHby] = anon_sym_satisfied_DASHby,
  [anon_sym_implemented_DASHby] = anon_sym_implemented_DASHby,
  [anon_sym_structured_DASHby] = anon_sym_structured_DASHby,
  [anon_sym_enforced_DASHby] = anon_sym_enforced_DASHby,
  [anon_sym_detected_DASHby] = anon_sym_detected_DASHby,
  [anon_sym_quality_DASHconstrained_DASHby] = anon_sym_quality_DASHconstrained_DASHby,
  [sym_satisfied_by_infrastructure] = sym_satisfied_by_infrastructure,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_string_literal] = sym_string_literal,
  [sym_type_name] = sym_type_name,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_requirement_set_def] = sym_requirement_set_def,
  [sym_module_block] = sym_module_block,
  [sym_prd_source_decl] = sym_prd_source_decl,
  [sym_requirement_def] = sym_requirement_def,
  [sym_ears_pattern] = sym_ears_pattern,
  [sym_ears_statement] = sym_ears_statement,
  [sym_rationale] = sym_rationale,
  [sym_moscow_priority] = sym_moscow_priority,
  [sym_source_decl] = sym_source_decl,
  [sym_depends_on_decl] = sym_depends_on_decl,
  [sym_conflicts_with_decl] = sym_conflicts_with_decl,
  [sym_decomposed_into_block] = sym_decomposed_into_block,
  [sym_satisfied_by_block] = sym_satisfied_by_block,
  [sym_implemented_by_clause] = sym_implemented_by_clause,
  [sym_structured_by_clause] = sym_structured_by_clause,
  [sym_enforced_by_clause] = sym_enforced_by_clause,
  [sym_detected_by_clause] = sym_detected_by_clause,
  [sym_quality_constrained_by_clause] = sym_quality_constrained_by_clause,
  [sym_domain_ref] = sym_domain_ref,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_requirement_set_def_repeat1] = aux_sym_requirement_set_def_repeat1,
  [aux_sym_module_block_repeat1] = aux_sym_module_block_repeat1,
  [aux_sym_requirement_def_repeat1] = aux_sym_requirement_def_repeat1,
  [aux_sym_requirement_def_repeat2] = aux_sym_requirement_def_repeat2,
  [aux_sym_depends_on_decl_repeat1] = aux_sym_depends_on_decl_repeat1,
  [aux_sym_decomposed_into_block_repeat1] = aux_sym_decomposed_into_block_repeat1,
  [aux_sym_satisfied_by_block_repeat1] = aux_sym_satisfied_by_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_requirements] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_scoped_DASHto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_prd_DASHsource] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_priority] = {
    .visible = true,
    .named = false,
  },
  [sym_requirement_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ubiquitous] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_state_DASHdriven] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_event_DASHdriven] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unwanted] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_optional] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_complex] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_must] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_should] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_could] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wont] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_source] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_depends_DASHon] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_conflicts_DASHwith] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decomposed_DASHinto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_satisfied_DASHby] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_implemented_DASHby] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_structured_DASHby] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enforced_DASHby] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_detected_DASHby] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_quality_DASHconstrained_DASHby] = {
    .visible = true,
    .named = false,
  },
  [sym_satisfied_by_infrastructure] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_requirement_set_def] = {
    .visible = true,
    .named = true,
  },
  [sym_module_block] = {
    .visible = true,
    .named = true,
  },
  [sym_prd_source_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_requirement_def] = {
    .visible = true,
    .named = true,
  },
  [sym_ears_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_ears_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_rationale] = {
    .visible = true,
    .named = true,
  },
  [sym_moscow_priority] = {
    .visible = true,
    .named = true,
  },
  [sym_source_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_depends_on_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_conflicts_with_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_decomposed_into_block] = {
    .visible = true,
    .named = true,
  },
  [sym_satisfied_by_block] = {
    .visible = true,
    .named = true,
  },
  [sym_implemented_by_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_structured_by_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_enforced_by_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_detected_by_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_quality_constrained_by_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_domain_ref] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_requirement_set_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_requirement_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_requirement_def_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_depends_on_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_decomposed_into_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_satisfied_by_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_id = 1,
  field_name = 2,
  field_path = 3,
  field_pattern = 4,
  field_priority = 5,
  field_reference = 6,
  field_scope = 7,
  field_statement = 8,
  field_text = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_id] = "id",
  [field_name] = "name",
  [field_path] = "path",
  [field_pattern] = "pattern",
  [field_priority] = "priority",
  [field_reference] = "reference",
  [field_scope] = "scope",
  [field_statement] = "statement",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 5},
  [7] = {.index = 11, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_scope, 3},
  [2] =
    {field_path, 1},
  [3] =
    {field_name, 1},
  [4] =
    {field_text, 1},
  [5] =
    {field_reference, 1},
  [6] =
    {field_id, 0},
    {field_name, 1},
    {field_pattern, 3},
    {field_priority, 6},
    {field_statement, 4},
  [11] =
    {field_id, 0},
    {field_name, 1},
    {field_pattern, 3},
    {field_priority, 7},
    {field_statement, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(269);
      ADVANCE_MAP(
        '"', 3,
        '#', 311,
        ',', 293,
        '.', 304,
        '/', 27,
        ':', 277,
        'R', 307,
        'c', 164,
        'd', 78,
        'e', 148,
        'i', 142,
        'm', 166,
        'o', 182,
        'p', 189,
        'q', 240,
        'r', 79,
        's', 35,
        'u', 40,
        'w', 167,
        '{', 272,
        '}', 273,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(309);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 3,
        '#', 311,
        ',', 293,
        '/', 27,
        ':', 28,
        'R', 29,
        'c', 178,
        'd', 86,
        'm', 165,
        'p', 195,
        's', 39,
        '}', 273,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(311);
      if (lookahead == '/') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(309);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(310);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(305);
      if (lookahead == '\\') ADVANCE(268);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '#', 311,
        '.', 304,
        '/', 27,
        ':', 276,
        'd', 101,
        'e', 147,
        'i', 142,
        'q', 240,
        's', 38,
        '}', 273,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(309);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(267);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(279);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(41);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(210);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(255);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(48);
      END_STATE();
    case 14:
      if (lookahead == '-') ADVANCE(54);
      END_STATE();
    case 15:
      if (lookahead == '-') ADVANCE(70);
      END_STATE();
    case 16:
      if (lookahead == '-') ADVANCE(129);
      END_STATE();
    case 17:
      if (lookahead == '-') ADVANCE(121);
      END_STATE();
    case 18:
      if (lookahead == '-') ADVANCE(173);
      END_STATE();
    case 19:
      if (lookahead == '-') ADVANCE(230);
      END_STATE();
    case 20:
      if (lookahead == '-') ADVANCE(42);
      END_STATE();
    case 21:
      if (lookahead == '-') ADVANCE(43);
      END_STATE();
    case 22:
      if (lookahead == '-') ADVANCE(44);
      END_STATE();
    case 23:
      if (lookahead == '-') ADVANCE(45);
      END_STATE();
    case 24:
      if (lookahead == '-') ADVANCE(46);
      END_STATE();
    case 25:
      if (lookahead == '-') ADVANCE(47);
      END_STATE();
    case 26:
      if (lookahead == '-') ADVANCE(72);
      END_STATE();
    case 27:
      if (lookahead == '/') ADVANCE(311);
      END_STATE();
    case 28:
      if (lookahead == ':') ADVANCE(286);
      END_STATE();
    case 29:
      if (lookahead == 'E') ADVANCE(30);
      END_STATE();
    case 30:
      if (lookahead == 'Q') ADVANCE(5);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(229);
      if (lookahead == 'r') ADVANCE(245);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(136);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(134);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(123);
      END_STATE();
    case 35:
      if (lookahead == 'a') ADVANCE(223);
      if (lookahead == 'c') ADVANCE(170);
      if (lookahead == 'h') ADVANCE(174);
      if (lookahead == 'o') ADVANCE(241);
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(213);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(161);
      END_STATE();
    case 38:
      if (lookahead == 'a') ADVANCE(237);
      if (lookahead == 't') ADVANCE(193);
      END_STATE();
    case 39:
      if (lookahead == 'a') ADVANCE(239);
      if (lookahead == 'o') ADVANCE(241);
      END_STATE();
    case 40:
      if (lookahead == 'b') ADVANCE(131);
      if (lookahead == 'n') ADVANCE(254);
      END_STATE();
    case 41:
      if (lookahead == 'b') ADVANCE(258);
      END_STATE();
    case 42:
      if (lookahead == 'b') ADVANCE(259);
      END_STATE();
    case 43:
      if (lookahead == 'b') ADVANCE(260);
      END_STATE();
    case 44:
      if (lookahead == 'b') ADVANCE(261);
      END_STATE();
    case 45:
      if (lookahead == 'b') ADVANCE(262);
      END_STATE();
    case 46:
      if (lookahead == 'b') ADVANCE(263);
      END_STATE();
    case 47:
      if (lookahead == 'b') ADVANCE(264);
      END_STATE();
    case 48:
      if (lookahead == 'b') ADVANCE(266);
      END_STATE();
    case 49:
      if (lookahead == 'c') ADVANCE(179);
      if (lookahead == 'p') ADVANCE(88);
      END_STATE();
    case 50:
      if (lookahead == 'c') ADVANCE(179);
      if (lookahead == 'p') ADVANCE(88);
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 51:
      if (lookahead == 'c') ADVANCE(227);
      END_STATE();
    case 52:
      if (lookahead == 'c') ADVANCE(235);
      END_STATE();
    case 53:
      if (lookahead == 'c') ADVANCE(83);
      END_STATE();
    case 54:
      if (lookahead == 'c') ADVANCE(176);
      END_STATE();
    case 55:
      if (lookahead == 'c') ADVANCE(84);
      END_STATE();
    case 56:
      if (lookahead == 'c') ADVANCE(231);
      END_STATE();
    case 57:
      if (lookahead == 'c') ADVANCE(97);
      END_STATE();
    case 58:
      if (lookahead == 'c') ADVANCE(238);
      END_STATE();
    case 59:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 60:
      if (lookahead == 'd') ADVANCE(11);
      if (lookahead == 'i') ADVANCE(171);
      END_STATE();
    case 61:
      if (lookahead == 'd') ADVANCE(289);
      END_STATE();
    case 62:
      if (lookahead == 'd') ADVANCE(288);
      END_STATE();
    case 63:
      if (lookahead == 'd') ADVANCE(283);
      END_STATE();
    case 64:
      if (lookahead == 'd') ADVANCE(247);
      END_STATE();
    case 65:
      if (lookahead == 'd') ADVANCE(19);
      END_STATE();
    case 66:
      if (lookahead == 'd') ADVANCE(208);
      END_STATE();
    case 67:
      if (lookahead == 'd') ADVANCE(10);
      END_STATE();
    case 68:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 69:
      if (lookahead == 'd') ADVANCE(13);
      END_STATE();
    case 70:
      if (lookahead == 'd') ADVANCE(194);
      END_STATE();
    case 71:
      if (lookahead == 'd') ADVANCE(20);
      END_STATE();
    case 72:
      if (lookahead == 'd') ADVANCE(199);
      END_STATE();
    case 73:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 74:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 75:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 76:
      if (lookahead == 'd') ADVANCE(24);
      END_STATE();
    case 77:
      if (lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 78:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 79:
      if (lookahead == 'e') ADVANCE(187);
      END_STATE();
    case 80:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 81:
      if (lookahead == 'e') ADVANCE(256);
      END_STATE();
    case 82:
      if (lookahead == 'e') ADVANCE(274);
      END_STATE();
    case 83:
      if (lookahead == 'e') ADVANCE(291);
      END_STATE();
    case 84:
      if (lookahead == 'e') ADVANCE(275);
      END_STATE();
    case 85:
      if (lookahead == 'e') ADVANCE(303);
      END_STATE();
    case 86:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 87:
      if (lookahead == 'e') ADVANCE(145);
      END_STATE();
    case 88:
      if (lookahead == 'e') ADVANCE(153);
      END_STATE();
    case 89:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 90:
      if (lookahead == 'e') ADVANCE(150);
      END_STATE();
    case 91:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 92:
      if (lookahead == 'e') ADVANCE(151);
      END_STATE();
    case 93:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 94:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 95:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 96:
      if (lookahead == 'e') ADVANCE(156);
      END_STATE();
    case 97:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 98:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 99:
      if (lookahead == 'e') ADVANCE(157);
      END_STATE();
    case 100:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 101:
      if (lookahead == 'e') ADVANCE(224);
      END_STATE();
    case 102:
      if (lookahead == 'e') ADVANCE(75);
      END_STATE();
    case 103:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 104:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 105:
      if (lookahead == 'e') ADVANCE(162);
      END_STATE();
    case 106:
      if (lookahead == 'e') ADVANCE(146);
      END_STATE();
    case 107:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 108:
      if (lookahead == 'f') ADVANCE(180);
      END_STATE();
    case 109:
      if (lookahead == 'f') ADVANCE(192);
      END_STATE();
    case 110:
      if (lookahead == 'f') ADVANCE(128);
      END_STATE();
    case 111:
      if (lookahead == 'f') ADVANCE(139);
      END_STATE();
    case 112:
      if (lookahead == 'f') ADVANCE(125);
      END_STATE();
    case 113:
      if (lookahead == 'f') ADVANCE(130);
      END_STATE();
    case 114:
      if (lookahead == 'h') ADVANCE(294);
      END_STATE();
    case 115:
      if (lookahead == 'i') ADVANCE(252);
      END_STATE();
    case 116:
      if (lookahead == 'i') ADVANCE(207);
      END_STATE();
    case 117:
      if (lookahead == 'i') ADVANCE(202);
      END_STATE();
    case 118:
      if (lookahead == 'i') ADVANCE(218);
      END_STATE();
    case 119:
      if (lookahead == 'i') ADVANCE(172);
      END_STATE();
    case 120:
      if (lookahead == 'i') ADVANCE(222);
      END_STATE();
    case 121:
      if (lookahead == 'i') ADVANCE(154);
      END_STATE();
    case 122:
      if (lookahead == 'i') ADVANCE(234);
      END_STATE();
    case 123:
      if (lookahead == 'i') ADVANCE(163);
      END_STATE();
    case 124:
      if (lookahead == 'i') ADVANCE(219);
      END_STATE();
    case 125:
      if (lookahead == 'i') ADVANCE(95);
      END_STATE();
    case 126:
      if (lookahead == 'i') ADVANCE(253);
      END_STATE();
    case 127:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 128:
      if (lookahead == 'i') ADVANCE(98);
      END_STATE();
    case 129:
      if (lookahead == 'i') ADVANCE(160);
      END_STATE();
    case 130:
      if (lookahead == 'i') ADVANCE(104);
      END_STATE();
    case 131:
      if (lookahead == 'i') ADVANCE(188);
      END_STATE();
    case 132:
      if (lookahead == 'i') ADVANCE(214);
      END_STATE();
    case 133:
      if (lookahead == 'i') ADVANCE(215);
      END_STATE();
    case 134:
      if (lookahead == 'l') ADVANCE(284);
      END_STATE();
    case 135:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 136:
      if (lookahead == 'l') ADVANCE(118);
      END_STATE();
    case 137:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 138:
      if (lookahead == 'l') ADVANCE(87);
      END_STATE();
    case 139:
      if (lookahead == 'l') ADVANCE(127);
      END_STATE();
    case 140:
      if (lookahead == 'l') ADVANCE(81);
      END_STATE();
    case 141:
      if (lookahead == 'l') ADVANCE(82);
      END_STATE();
    case 142:
      if (lookahead == 'm') ADVANCE(183);
      END_STATE();
    case 143:
      if (lookahead == 'm') ADVANCE(185);
      END_STATE();
    case 144:
      if (lookahead == 'm') ADVANCE(186);
      if (lookahead == 'n') ADVANCE(111);
      if (lookahead == 'u') ADVANCE(135);
      END_STATE();
    case 145:
      if (lookahead == 'm') ADVANCE(105);
      END_STATE();
    case 146:
      if (lookahead == 'm') ADVANCE(99);
      END_STATE();
    case 147:
      if (lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 148:
      if (lookahead == 'n') ADVANCE(108);
      if (lookahead == 'v') ADVANCE(96);
      END_STATE();
    case 149:
      if (lookahead == 'n') ADVANCE(292);
      END_STATE();
    case 150:
      if (lookahead == 'n') ADVANCE(282);
      END_STATE();
    case 151:
      if (lookahead == 'n') ADVANCE(281);
      END_STATE();
    case 152:
      if (lookahead == 'n') ADVANCE(111);
      END_STATE();
    case 153:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 154:
      if (lookahead == 'n') ADVANCE(109);
      END_STATE();
    case 155:
      if (lookahead == 'n') ADVANCE(217);
      END_STATE();
    case 156:
      if (lookahead == 'n') ADVANCE(221);
      END_STATE();
    case 157:
      if (lookahead == 'n') ADVANCE(228);
      END_STATE();
    case 158:
      if (lookahead == 'n') ADVANCE(212);
      END_STATE();
    case 159:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 160:
      if (lookahead == 'n') ADVANCE(233);
      END_STATE();
    case 161:
      if (lookahead == 'n') ADVANCE(232);
      END_STATE();
    case 162:
      if (lookahead == 'n') ADVANCE(236);
      END_STATE();
    case 163:
      if (lookahead == 'n') ADVANCE(103);
      END_STATE();
    case 164:
      if (lookahead == 'o') ADVANCE(144);
      END_STATE();
    case 165:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 166:
      if (lookahead == 'o') ADVANCE(64);
      if (lookahead == 'u') ADVANCE(206);
      END_STATE();
    case 167:
      if (lookahead == 'o') ADVANCE(155);
      END_STATE();
    case 168:
      if (lookahead == 'o') ADVANCE(271);
      END_STATE();
    case 169:
      if (lookahead == 'o') ADVANCE(295);
      END_STATE();
    case 170:
      if (lookahead == 'o') ADVANCE(184);
      END_STATE();
    case 171:
      if (lookahead == 'o') ADVANCE(198);
      END_STATE();
    case 172:
      if (lookahead == 'o') ADVANCE(159);
      END_STATE();
    case 173:
      if (lookahead == 'o') ADVANCE(149);
      END_STATE();
    case 174:
      if (lookahead == 'o') ADVANCE(244);
      END_STATE();
    case 175:
      if (lookahead == 'o') ADVANCE(211);
      END_STATE();
    case 176:
      if (lookahead == 'o') ADVANCE(158);
      END_STATE();
    case 177:
      if (lookahead == 'o') ADVANCE(243);
      END_STATE();
    case 178:
      if (lookahead == 'o') ADVANCE(152);
      END_STATE();
    case 179:
      if (lookahead == 'o') ADVANCE(143);
      END_STATE();
    case 180:
      if (lookahead == 'o') ADVANCE(197);
      END_STATE();
    case 181:
      if (lookahead == 'o') ADVANCE(251);
      END_STATE();
    case 182:
      if (lookahead == 'p') ADVANCE(220);
      END_STATE();
    case 183:
      if (lookahead == 'p') ADVANCE(138);
      END_STATE();
    case 184:
      if (lookahead == 'p') ADVANCE(89);
      END_STATE();
    case 185:
      if (lookahead == 'p') ADVANCE(175);
      END_STATE();
    case 186:
      if (lookahead == 'p') ADVANCE(140);
      END_STATE();
    case 187:
      if (lookahead == 'q') ADVANCE(242);
      END_STATE();
    case 188:
      if (lookahead == 'q') ADVANCE(249);
      END_STATE();
    case 189:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 190:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 191:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 192:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 193:
      if (lookahead == 'r') ADVANCE(245);
      END_STATE();
    case 194:
      if (lookahead == 'r') ADVANCE(115);
      END_STATE();
    case 195:
      if (lookahead == 'r') ADVANCE(59);
      END_STATE();
    case 196:
      if (lookahead == 'r') ADVANCE(85);
      END_STATE();
    case 197:
      if (lookahead == 'r') ADVANCE(57);
      END_STATE();
    case 198:
      if (lookahead == 'r') ADVANCE(120);
      END_STATE();
    case 199:
      if (lookahead == 'r') ADVANCE(126);
      END_STATE();
    case 200:
      if (lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 201:
      if (lookahead == 'r') ADVANCE(100);
      END_STATE();
    case 202:
      if (lookahead == 'r') ADVANCE(106);
      END_STATE();
    case 203:
      if (lookahead == 'r') ADVANCE(250);
      END_STATE();
    case 204:
      if (lookahead == 's') ADVANCE(280);
      END_STATE();
    case 205:
      if (lookahead == 's') ADVANCE(270);
      END_STATE();
    case 206:
      if (lookahead == 's') ADVANCE(216);
      END_STATE();
    case 207:
      if (lookahead == 's') ADVANCE(110);
      END_STATE();
    case 208:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 209:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 210:
      if (lookahead == 's') ADVANCE(181);
      END_STATE();
    case 211:
      if (lookahead == 's') ADVANCE(94);
      END_STATE();
    case 212:
      if (lookahead == 's') ADVANCE(225);
      END_STATE();
    case 213:
      if (lookahead == 's') ADVANCE(226);
      END_STATE();
    case 214:
      if (lookahead == 's') ADVANCE(112);
      END_STATE();
    case 215:
      if (lookahead == 's') ADVANCE(113);
      END_STATE();
    case 216:
      if (lookahead == 't') ADVANCE(287);
      END_STATE();
    case 217:
      if (lookahead == 't') ADVANCE(290);
      END_STATE();
    case 218:
      if (lookahead == 't') ADVANCE(265);
      END_STATE();
    case 219:
      if (lookahead == 't') ADVANCE(114);
      END_STATE();
    case 220:
      if (lookahead == 't') ADVANCE(119);
      END_STATE();
    case 221:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 222:
      if (lookahead == 't') ADVANCE(257);
      END_STATE();
    case 223:
      if (lookahead == 't') ADVANCE(116);
      END_STATE();
    case 224:
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 225:
      if (lookahead == 't') ADVANCE(191);
      END_STATE();
    case 226:
      if (lookahead == 't') ADVANCE(203);
      END_STATE();
    case 227:
      if (lookahead == 't') ADVANCE(246);
      END_STATE();
    case 228:
      if (lookahead == 't') ADVANCE(205);
      END_STATE();
    case 229:
      if (lookahead == 't') ADVANCE(107);
      END_STATE();
    case 230:
      if (lookahead == 't') ADVANCE(168);
      END_STATE();
    case 231:
      if (lookahead == 't') ADVANCE(91);
      END_STATE();
    case 232:
      if (lookahead == 't') ADVANCE(93);
      END_STATE();
    case 233:
      if (lookahead == 't') ADVANCE(169);
      END_STATE();
    case 234:
      if (lookahead == 't') ADVANCE(177);
      END_STATE();
    case 235:
      if (lookahead == 't') ADVANCE(209);
      END_STATE();
    case 236:
      if (lookahead == 't') ADVANCE(102);
      END_STATE();
    case 237:
      if (lookahead == 't') ADVANCE(132);
      END_STATE();
    case 238:
      if (lookahead == 't') ADVANCE(248);
      END_STATE();
    case 239:
      if (lookahead == 't') ADVANCE(133);
      END_STATE();
    case 240:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 241:
      if (lookahead == 'u') ADVANCE(190);
      END_STATE();
    case 242:
      if (lookahead == 'u') ADVANCE(117);
      END_STATE();
    case 243:
      if (lookahead == 'u') ADVANCE(204);
      END_STATE();
    case 244:
      if (lookahead == 'u') ADVANCE(137);
      END_STATE();
    case 245:
      if (lookahead == 'u') ADVANCE(51);
      END_STATE();
    case 246:
      if (lookahead == 'u') ADVANCE(201);
      END_STATE();
    case 247:
      if (lookahead == 'u') ADVANCE(141);
      END_STATE();
    case 248:
      if (lookahead == 'u') ADVANCE(196);
      END_STATE();
    case 249:
      if (lookahead == 'u') ADVANCE(122);
      END_STATE();
    case 250:
      if (lookahead == 'u') ADVANCE(58);
      END_STATE();
    case 251:
      if (lookahead == 'u') ADVANCE(200);
      END_STATE();
    case 252:
      if (lookahead == 'v') ADVANCE(90);
      END_STATE();
    case 253:
      if (lookahead == 'v') ADVANCE(92);
      END_STATE();
    case 254:
      if (lookahead == 'w') ADVANCE(37);
      END_STATE();
    case 255:
      if (lookahead == 'w') ADVANCE(124);
      END_STATE();
    case 256:
      if (lookahead == 'x') ADVANCE(285);
      END_STATE();
    case 257:
      if (lookahead == 'y') ADVANCE(278);
      END_STATE();
    case 258:
      if (lookahead == 'y') ADVANCE(301);
      END_STATE();
    case 259:
      if (lookahead == 'y') ADVANCE(300);
      END_STATE();
    case 260:
      if (lookahead == 'y') ADVANCE(297);
      END_STATE();
    case 261:
      if (lookahead == 'y') ADVANCE(299);
      END_STATE();
    case 262:
      if (lookahead == 'y') ADVANCE(298);
      END_STATE();
    case 263:
      if (lookahead == 'y') ADVANCE(302);
      END_STATE();
    case 264:
      if (lookahead == 'y') ADVANCE(296);
      END_STATE();
    case 265:
      if (lookahead == 'y') ADVANCE(14);
      END_STATE();
    case 266:
      if (lookahead == 'y') ADVANCE(17);
      END_STATE();
    case 267:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 268:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 269:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 270:
      ACCEPT_TOKEN(anon_sym_requirements);
      END_STATE();
    case 271:
      ACCEPT_TOKEN(anon_sym_scoped_DASHto);
      END_STATE();
    case 272:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 273:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 274:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 275:
      ACCEPT_TOKEN(anon_sym_prd_DASHsource);
      END_STATE();
    case 276:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 277:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(286);
      END_STATE();
    case 278:
      ACCEPT_TOKEN(anon_sym_priority);
      END_STATE();
    case 279:
      ACCEPT_TOKEN(sym_requirement_id);
      if (lookahead == '-') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 280:
      ACCEPT_TOKEN(anon_sym_ubiquitous);
      END_STATE();
    case 281:
      ACCEPT_TOKEN(anon_sym_state_DASHdriven);
      END_STATE();
    case 282:
      ACCEPT_TOKEN(anon_sym_event_DASHdriven);
      END_STATE();
    case 283:
      ACCEPT_TOKEN(anon_sym_unwanted);
      END_STATE();
    case 284:
      ACCEPT_TOKEN(anon_sym_optional);
      END_STATE();
    case 285:
      ACCEPT_TOKEN(anon_sym_complex);
      END_STATE();
    case 286:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 287:
      ACCEPT_TOKEN(anon_sym_must);
      END_STATE();
    case 288:
      ACCEPT_TOKEN(anon_sym_should);
      END_STATE();
    case 289:
      ACCEPT_TOKEN(anon_sym_could);
      END_STATE();
    case 290:
      ACCEPT_TOKEN(anon_sym_wont);
      END_STATE();
    case 291:
      ACCEPT_TOKEN(anon_sym_source);
      END_STATE();
    case 292:
      ACCEPT_TOKEN(anon_sym_depends_DASHon);
      END_STATE();
    case 293:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 294:
      ACCEPT_TOKEN(anon_sym_conflicts_DASHwith);
      END_STATE();
    case 295:
      ACCEPT_TOKEN(anon_sym_decomposed_DASHinto);
      END_STATE();
    case 296:
      ACCEPT_TOKEN(anon_sym_satisfied_DASHby);
      END_STATE();
    case 297:
      ACCEPT_TOKEN(anon_sym_satisfied_DASHby);
      if (lookahead == '-') ADVANCE(121);
      END_STATE();
    case 298:
      ACCEPT_TOKEN(anon_sym_implemented_DASHby);
      END_STATE();
    case 299:
      ACCEPT_TOKEN(anon_sym_structured_DASHby);
      END_STATE();
    case 300:
      ACCEPT_TOKEN(anon_sym_enforced_DASHby);
      END_STATE();
    case 301:
      ACCEPT_TOKEN(anon_sym_detected_DASHby);
      END_STATE();
    case 302:
      ACCEPT_TOKEN(anon_sym_quality_DASHconstrained_DASHby);
      END_STATE();
    case 303:
      ACCEPT_TOKEN(sym_satisfied_by_infrastructure);
      END_STATE();
    case 304:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 305:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 306:
      ACCEPT_TOKEN(sym_type_name);
      if (lookahead == '-') ADVANCE(267);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(309);
      END_STATE();
    case 307:
      ACCEPT_TOKEN(sym_type_name);
      if (lookahead == 'E') ADVANCE(308);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(309);
      END_STATE();
    case 308:
      ACCEPT_TOKEN(sym_type_name);
      if (lookahead == 'Q') ADVANCE(306);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(309);
      END_STATE();
    case 309:
      ACCEPT_TOKEN(sym_type_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(309);
      END_STATE();
    case 310:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(310);
      END_STATE();
    case 311:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(311);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_requirements] = ACTIONS(1),
    [anon_sym_scoped_DASHto] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_prd_DASHsource] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_priority] = ACTIONS(1),
    [sym_requirement_id] = ACTIONS(1),
    [anon_sym_ubiquitous] = ACTIONS(1),
    [anon_sym_state_DASHdriven] = ACTIONS(1),
    [anon_sym_event_DASHdriven] = ACTIONS(1),
    [anon_sym_unwanted] = ACTIONS(1),
    [anon_sym_optional] = ACTIONS(1),
    [anon_sym_complex] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_must] = ACTIONS(1),
    [anon_sym_should] = ACTIONS(1),
    [anon_sym_could] = ACTIONS(1),
    [anon_sym_wont] = ACTIONS(1),
    [anon_sym_source] = ACTIONS(1),
    [anon_sym_depends_DASHon] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_conflicts_DASHwith] = ACTIONS(1),
    [anon_sym_decomposed_DASHinto] = ACTIONS(1),
    [anon_sym_satisfied_DASHby] = ACTIONS(1),
    [anon_sym_implemented_DASHby] = ACTIONS(1),
    [anon_sym_structured_DASHby] = ACTIONS(1),
    [anon_sym_enforced_DASHby] = ACTIONS(1),
    [anon_sym_detected_DASHby] = ACTIONS(1),
    [anon_sym_quality_DASHconstrained_DASHby] = ACTIONS(1),
    [sym_satisfied_by_infrastructure] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_type_name] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(61),
    [sym_requirement_set_def] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_requirements] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(11), 1,
      anon_sym_source,
    ACTIONS(13), 1,
      anon_sym_depends_DASHon,
    ACTIONS(15), 1,
      anon_sym_conflicts_DASHwith,
    ACTIONS(17), 1,
      anon_sym_decomposed_DASHinto,
    ACTIONS(19), 1,
      anon_sym_satisfied_DASHby,
    ACTIONS(21), 1,
      sym_string_literal,
    STATE(71), 1,
      sym_ears_statement,
    STATE(4), 7,
      sym_rationale,
      sym_source_decl,
      sym_depends_on_decl,
      sym_conflicts_with_decl,
      sym_decomposed_into_block,
      sym_satisfied_by_block,
      aux_sym_requirement_def_repeat1,
  [37] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(11), 1,
      anon_sym_source,
    ACTIONS(13), 1,
      anon_sym_depends_DASHon,
    ACTIONS(15), 1,
      anon_sym_conflicts_DASHwith,
    ACTIONS(17), 1,
      anon_sym_decomposed_DASHinto,
    ACTIONS(19), 1,
      anon_sym_satisfied_DASHby,
    ACTIONS(21), 1,
      sym_string_literal,
    STATE(64), 1,
      sym_ears_statement,
    STATE(2), 7,
      sym_rationale,
      sym_source_decl,
      sym_depends_on_decl,
      sym_conflicts_with_decl,
      sym_decomposed_into_block,
      sym_satisfied_by_block,
      aux_sym_requirement_def_repeat1,
  [74] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COLON_COLON,
    ACTIONS(26), 1,
      anon_sym_source,
    ACTIONS(29), 1,
      anon_sym_depends_DASHon,
    ACTIONS(32), 1,
      anon_sym_conflicts_DASHwith,
    ACTIONS(35), 1,
      anon_sym_decomposed_DASHinto,
    ACTIONS(38), 1,
      anon_sym_satisfied_DASHby,
    ACTIONS(41), 1,
      sym_string_literal,
    STATE(4), 7,
      sym_rationale,
      sym_source_decl,
      sym_depends_on_decl,
      sym_conflicts_with_decl,
      sym_decomposed_into_block,
      sym_satisfied_by_block,
      aux_sym_requirement_def_repeat1,
  [108] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_COMMA,
    STATE(9), 1,
      aux_sym_depends_on_decl_repeat1,
    ACTIONS(43), 11,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [131] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_depends_on_decl_repeat1,
    ACTIONS(47), 11,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [154] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_COMMA,
    STATE(6), 1,
      aux_sym_depends_on_decl_repeat1,
    ACTIONS(49), 11,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [177] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 1,
      anon_sym_implemented_DASHby,
    ACTIONS(55), 1,
      anon_sym_structured_DASHby,
    ACTIONS(57), 1,
      anon_sym_enforced_DASHby,
    ACTIONS(59), 1,
      anon_sym_detected_DASHby,
    ACTIONS(61), 1,
      anon_sym_quality_DASHconstrained_DASHby,
    ACTIONS(63), 1,
      sym_satisfied_by_infrastructure,
    STATE(10), 6,
      sym_implemented_by_clause,
      sym_structured_by_clause,
      sym_enforced_by_clause,
      sym_detected_by_clause,
      sym_quality_constrained_by_clause,
      aux_sym_satisfied_by_block_repeat1,
  [210] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_depends_on_decl_repeat1,
    ACTIONS(65), 11,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [233] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_implemented_DASHby,
    ACTIONS(55), 1,
      anon_sym_structured_DASHby,
    ACTIONS(57), 1,
      anon_sym_enforced_DASHby,
    ACTIONS(59), 1,
      anon_sym_detected_DASHby,
    ACTIONS(61), 1,
      anon_sym_quality_DASHconstrained_DASHby,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    ACTIONS(69), 1,
      sym_satisfied_by_infrastructure,
    STATE(16), 6,
      sym_implemented_by_clause,
      sym_structured_by_clause,
      sym_enforced_by_clause,
      sym_detected_by_clause,
      sym_quality_constrained_by_clause,
      aux_sym_satisfied_by_block_repeat1,
  [266] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_depends_DASHon,
    ACTIONS(15), 1,
      anon_sym_conflicts_DASHwith,
    ACTIONS(17), 1,
      anon_sym_decomposed_DASHinto,
    ACTIONS(19), 1,
      anon_sym_satisfied_DASHby,
    ACTIONS(71), 4,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
    STATE(15), 5,
      sym_depends_on_decl,
      sym_conflicts_with_decl,
      sym_decomposed_into_block,
      sym_satisfied_by_block,
      aux_sym_requirement_def_repeat2,
  [295] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_depends_DASHon,
    ACTIONS(15), 1,
      anon_sym_conflicts_DASHwith,
    ACTIONS(17), 1,
      anon_sym_decomposed_DASHinto,
    ACTIONS(19), 1,
      anon_sym_satisfied_DASHby,
    ACTIONS(73), 4,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
    STATE(11), 5,
      sym_depends_on_decl,
      sym_conflicts_with_decl,
      sym_decomposed_into_block,
      sym_satisfied_by_block,
      aux_sym_requirement_def_repeat2,
  [324] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_depends_on_decl_repeat1,
    ACTIONS(75), 11,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [347] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_depends_DASHon,
    ACTIONS(15), 1,
      anon_sym_conflicts_DASHwith,
    ACTIONS(17), 1,
      anon_sym_decomposed_DASHinto,
    ACTIONS(19), 1,
      anon_sym_satisfied_DASHby,
    ACTIONS(80), 4,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
    STATE(17), 5,
      sym_depends_on_decl,
      sym_conflicts_with_decl,
      sym_decomposed_into_block,
      sym_satisfied_by_block,
      aux_sym_requirement_def_repeat2,
  [376] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_depends_DASHon,
    ACTIONS(87), 1,
      anon_sym_conflicts_DASHwith,
    ACTIONS(90), 1,
      anon_sym_decomposed_DASHinto,
    ACTIONS(93), 1,
      anon_sym_satisfied_DASHby,
    ACTIONS(82), 4,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
    STATE(15), 5,
      sym_depends_on_decl,
      sym_conflicts_with_decl,
      sym_decomposed_into_block,
      sym_satisfied_by_block,
      aux_sym_requirement_def_repeat2,
  [405] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(98), 1,
      anon_sym_implemented_DASHby,
    ACTIONS(101), 1,
      anon_sym_structured_DASHby,
    ACTIONS(104), 1,
      anon_sym_enforced_DASHby,
    ACTIONS(107), 1,
      anon_sym_detected_DASHby,
    ACTIONS(110), 1,
      anon_sym_quality_DASHconstrained_DASHby,
    ACTIONS(113), 1,
      sym_satisfied_by_infrastructure,
    STATE(16), 6,
      sym_implemented_by_clause,
      sym_structured_by_clause,
      sym_enforced_by_clause,
      sym_detected_by_clause,
      sym_quality_constrained_by_clause,
      aux_sym_satisfied_by_block_repeat1,
  [438] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_depends_DASHon,
    ACTIONS(15), 1,
      anon_sym_conflicts_DASHwith,
    ACTIONS(17), 1,
      anon_sym_decomposed_DASHinto,
    ACTIONS(19), 1,
      anon_sym_satisfied_DASHby,
    ACTIONS(116), 4,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
    STATE(15), 5,
      sym_depends_on_decl,
      sym_conflicts_with_decl,
      sym_decomposed_into_block,
      sym_satisfied_by_block,
      aux_sym_requirement_def_repeat2,
  [467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 12,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_COMMA,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [485] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 11,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [502] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 11,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [519] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 11,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [536] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    ACTIONS(126), 1,
      anon_sym_module,
    ACTIONS(128), 1,
      anon_sym_prd_DASHsource,
    ACTIONS(130), 1,
      sym_requirement_id,
    STATE(23), 4,
      sym_module_block,
      sym_prd_source_decl,
      sym_requirement_def,
      aux_sym_requirement_set_def_repeat1,
  [558] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    ACTIONS(134), 1,
      anon_sym_module,
    ACTIONS(137), 1,
      anon_sym_prd_DASHsource,
    ACTIONS(140), 1,
      sym_requirement_id,
    STATE(23), 4,
      sym_module_block,
      sym_prd_source_decl,
      sym_requirement_def,
      aux_sym_requirement_set_def_repeat1,
  [580] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_module,
    ACTIONS(128), 1,
      anon_sym_prd_DASHsource,
    ACTIONS(130), 1,
      sym_requirement_id,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(22), 4,
      sym_module_block,
      sym_prd_source_decl,
      sym_requirement_def,
      aux_sym_requirement_set_def_repeat1,
  [602] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_DOT,
    ACTIONS(145), 7,
      anon_sym_RBRACE,
      anon_sym_implemented_DASHby,
      anon_sym_structured_DASHby,
      anon_sym_enforced_DASHby,
      anon_sym_detected_DASHby,
      anon_sym_quality_DASHconstrained_DASHby,
      sym_satisfied_by_infrastructure,
  [618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 8,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
  [632] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 7,
      anon_sym_RBRACE,
      anon_sym_implemented_DASHby,
      anon_sym_structured_DASHby,
      anon_sym_enforced_DASHby,
      anon_sym_detected_DASHby,
      anon_sym_quality_DASHconstrained_DASHby,
      sym_satisfied_by_infrastructure,
  [645] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 7,
      anon_sym_RBRACE,
      anon_sym_implemented_DASHby,
      anon_sym_structured_DASHby,
      anon_sym_enforced_DASHby,
      anon_sym_detected_DASHby,
      anon_sym_quality_DASHconstrained_DASHby,
      sym_satisfied_by_infrastructure,
  [658] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 7,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [671] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 7,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [684] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 7,
      anon_sym_RBRACE,
      anon_sym_implemented_DASHby,
      anon_sym_structured_DASHby,
      anon_sym_enforced_DASHby,
      anon_sym_detected_DASHby,
      anon_sym_quality_DASHconstrained_DASHby,
      sym_satisfied_by_infrastructure,
  [697] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 7,
      anon_sym_RBRACE,
      anon_sym_implemented_DASHby,
      anon_sym_structured_DASHby,
      anon_sym_enforced_DASHby,
      anon_sym_detected_DASHby,
      anon_sym_quality_DASHconstrained_DASHby,
      sym_satisfied_by_infrastructure,
  [710] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(3), 1,
      sym_ears_pattern,
    ACTIONS(163), 6,
      anon_sym_ubiquitous,
      anon_sym_state_DASHdriven,
      anon_sym_event_DASHdriven,
      anon_sym_unwanted,
      anon_sym_optional,
      anon_sym_complex,
  [725] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 7,
      anon_sym_RBRACE,
      anon_sym_implemented_DASHby,
      anon_sym_structured_DASHby,
      anon_sym_enforced_DASHby,
      anon_sym_detected_DASHby,
      anon_sym_quality_DASHconstrained_DASHby,
      sym_satisfied_by_infrastructure,
  [738] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 7,
      anon_sym_RBRACE,
      anon_sym_implemented_DASHby,
      anon_sym_structured_DASHby,
      anon_sym_enforced_DASHby,
      anon_sym_detected_DASHby,
      anon_sym_quality_DASHconstrained_DASHby,
      sym_satisfied_by_infrastructure,
  [751] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 7,
      anon_sym_COLON_COLON,
      anon_sym_source,
      anon_sym_depends_DASHon,
      anon_sym_conflicts_DASHwith,
      anon_sym_decomposed_DASHinto,
      anon_sym_satisfied_DASHby,
      sym_string_literal,
  [764] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(14), 1,
      sym_moscow_priority,
    ACTIONS(171), 4,
      anon_sym_must,
      anon_sym_should,
      anon_sym_could,
      anon_sym_wont,
  [777] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(12), 1,
      sym_moscow_priority,
    ACTIONS(171), 4,
      anon_sym_must,
      anon_sym_should,
      anon_sym_could,
      anon_sym_wont,
  [790] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 1,
      anon_sym_requirements,
    STATE(39), 2,
      sym_requirement_set_def,
      aux_sym_source_file_repeat1,
  [804] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 4,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
  [814] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_requirements,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    STATE(39), 2,
      sym_requirement_set_def,
      aux_sym_source_file_repeat1,
  [828] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      sym_requirement_id,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    STATE(43), 2,
      sym_requirement_def,
      aux_sym_module_block_repeat1,
  [842] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      sym_requirement_id,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(46), 2,
      sym_requirement_def,
      aux_sym_module_block_repeat1,
  [856] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 4,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
  [866] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 4,
      anon_sym_RBRACE,
      anon_sym_module,
      anon_sym_prd_DASHsource,
      sym_requirement_id,
  [876] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    ACTIONS(192), 1,
      sym_requirement_id,
    STATE(46), 2,
      sym_requirement_def,
      aux_sym_module_block_repeat1,
  [890] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(32), 1,
      sym_domain_ref,
    ACTIONS(195), 2,
      sym_type_name,
      sym_identifier,
  [901] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym_domain_ref,
    ACTIONS(195), 2,
      sym_type_name,
      sym_identifier,
  [912] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      sym_requirement_id,
    STATE(53), 1,
      aux_sym_decomposed_into_block_repeat1,
  [925] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(31), 1,
      sym_domain_ref,
    ACTIONS(195), 2,
      sym_type_name,
      sym_identifier,
  [936] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(34), 1,
      sym_domain_ref,
    ACTIONS(195), 2,
      sym_type_name,
      sym_identifier,
  [947] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(35), 1,
      sym_domain_ref,
    ACTIONS(195), 2,
      sym_type_name,
      sym_identifier,
  [958] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    ACTIONS(203), 1,
      sym_requirement_id,
    STATE(53), 1,
      aux_sym_decomposed_into_block_repeat1,
  [971] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 2,
      ts_builtin_sym_end,
      anon_sym_requirements,
  [979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 2,
      ts_builtin_sym_end,
      anon_sym_requirements,
  [987] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_requirement_id,
    STATE(49), 1,
      aux_sym_decomposed_into_block_repeat1,
  [997] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 2,
      sym_string_literal,
      sym_identifier,
  [1005] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      sym_string_literal,
  [1012] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      sym_string_literal,
  [1019] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      sym_string_literal,
  [1026] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
  [1033] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_LBRACE,
  [1040] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_priority,
  [1047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_priority,
  [1054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_COLON,
  [1061] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym_requirement_id,
  [1068] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_type_name,
  [1075] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_requirement_id,
  [1082] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_string_literal,
  [1089] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
  [1096] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_priority,
  [1103] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
  [1110] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_scoped_DASHto,
  [1117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_LBRACE,
  [1124] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      sym_requirement_id,
  [1131] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_string_literal,
  [1138] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_string_literal,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 131,
  [SMALL_STATE(7)] = 154,
  [SMALL_STATE(8)] = 177,
  [SMALL_STATE(9)] = 210,
  [SMALL_STATE(10)] = 233,
  [SMALL_STATE(11)] = 266,
  [SMALL_STATE(12)] = 295,
  [SMALL_STATE(13)] = 324,
  [SMALL_STATE(14)] = 347,
  [SMALL_STATE(15)] = 376,
  [SMALL_STATE(16)] = 405,
  [SMALL_STATE(17)] = 438,
  [SMALL_STATE(18)] = 467,
  [SMALL_STATE(19)] = 485,
  [SMALL_STATE(20)] = 502,
  [SMALL_STATE(21)] = 519,
  [SMALL_STATE(22)] = 536,
  [SMALL_STATE(23)] = 558,
  [SMALL_STATE(24)] = 580,
  [SMALL_STATE(25)] = 602,
  [SMALL_STATE(26)] = 618,
  [SMALL_STATE(27)] = 632,
  [SMALL_STATE(28)] = 645,
  [SMALL_STATE(29)] = 658,
  [SMALL_STATE(30)] = 671,
  [SMALL_STATE(31)] = 684,
  [SMALL_STATE(32)] = 697,
  [SMALL_STATE(33)] = 710,
  [SMALL_STATE(34)] = 725,
  [SMALL_STATE(35)] = 738,
  [SMALL_STATE(36)] = 751,
  [SMALL_STATE(37)] = 764,
  [SMALL_STATE(38)] = 777,
  [SMALL_STATE(39)] = 790,
  [SMALL_STATE(40)] = 804,
  [SMALL_STATE(41)] = 814,
  [SMALL_STATE(42)] = 828,
  [SMALL_STATE(43)] = 842,
  [SMALL_STATE(44)] = 856,
  [SMALL_STATE(45)] = 866,
  [SMALL_STATE(46)] = 876,
  [SMALL_STATE(47)] = 890,
  [SMALL_STATE(48)] = 901,
  [SMALL_STATE(49)] = 912,
  [SMALL_STATE(50)] = 925,
  [SMALL_STATE(51)] = 936,
  [SMALL_STATE(52)] = 947,
  [SMALL_STATE(53)] = 958,
  [SMALL_STATE(54)] = 971,
  [SMALL_STATE(55)] = 979,
  [SMALL_STATE(56)] = 987,
  [SMALL_STATE(57)] = 997,
  [SMALL_STATE(58)] = 1005,
  [SMALL_STATE(59)] = 1012,
  [SMALL_STATE(60)] = 1019,
  [SMALL_STATE(61)] = 1026,
  [SMALL_STATE(62)] = 1033,
  [SMALL_STATE(63)] = 1040,
  [SMALL_STATE(64)] = 1047,
  [SMALL_STATE(65)] = 1054,
  [SMALL_STATE(66)] = 1061,
  [SMALL_STATE(67)] = 1068,
  [SMALL_STATE(68)] = 1075,
  [SMALL_STATE(69)] = 1082,
  [SMALL_STATE(70)] = 1089,
  [SMALL_STATE(71)] = 1096,
  [SMALL_STATE(72)] = 1103,
  [SMALL_STATE(73)] = 1110,
  [SMALL_STATE(74)] = 1117,
  [SMALL_STATE(75)] = 1124,
  [SMALL_STATE(76)] = 1131,
  [SMALL_STATE(77)] = 1138,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conflicts_with_decl, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depends_on_decl, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depends_on_decl, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conflicts_with_decl, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requirement_def, 8, 0, 6),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requirement_def, 7, 0, 6),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depends_on_decl_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_depends_on_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requirement_def, 8, 0, 7),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat2, 2, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat2, 2, 0, 0), SHIFT_REPEAT(66),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat2, 2, 0, 0), SHIFT_REPEAT(68),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat2, 2, 0, 0), SHIFT_REPEAT(72),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_def_repeat2, 2, 0, 0), SHIFT_REPEAT(70),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_satisfied_by_block_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_satisfied_by_block_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_satisfied_by_block_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_satisfied_by_block_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_satisfied_by_block_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_satisfied_by_block_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_satisfied_by_block_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requirement_def, 9, 0, 7),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_satisfied_by_block, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_satisfied_by_block, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decomposed_into_block, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_requirement_set_def_repeat1, 2, 0, 0),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_set_def_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_set_def_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_set_def_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain_ref, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_moscow_priority, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enforced_by_clause, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain_ref, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_decl, 2, 0, 5),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rationale, 2, 0, 4),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_implemented_by_clause, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_structured_by_clause, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_detected_by_clause, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quality_constrained_by_clause, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ears_pattern, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prd_source_decl, 2, 0, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_block, 4, 0, 3),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_block, 5, 0, 3),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_block_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_block_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_decomposed_into_block_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_decomposed_into_block_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requirement_set_def, 7, 0, 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requirement_set_def, 6, 0, 1),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [220] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ears_statement, 1, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_specy_sysreq(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "specy_sysreq",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
