/* Sample domain-model instances conforming to src/metamodels/DOMAIN-METAMODEL.md.
   Ids are globally unique; any `ref:` / `refs:` value is an element id and
   renders as a navigation link. */

const MODEL = {
  organizations: [
    {
      id: "acme-mobility",
      name: "Acme Mobility",
      description: "Ride-hailing operator. Three bounded contexts: ride-hailing (core), payments (supporting), driver-fleet (supporting).",
      requirementsSource: "specy/acme-mobility.sysreq",
      contexts: [
        {
          id: "ride-hailing",
          name: "Ride Hailing",
          shortname: "rh",
          description: "The core context: a rider requests a ride, a driver is matched, the ride is fulfilled. Owns the ride lifecycle end to end.",
          relations: [
            { with: "payments", position: "downstream", pattern: "ACL",
              note: "Payment concepts are translated at the boundary; PaymentSettled is the only fact this context reacts to." },
            { with: "driver-fleet", position: "downstream", pattern: "Customer/Supplier",
              note: "Driver availability shapes matching; the fleet team accepts interface requests from ride-hailing." },
          ],
          modules: [
            {
              id: "rh.rides", name: "rides",
              description: "Ride lifecycle: request, match, fulfil, cancel. The module's public surface is the RideAPI; it depends on driver-location and persistence SPIs.",
              elements: [
                {
                  id: "rh.rides.Ride", kind: "aggregate", name: "Ride",
                  description: "The ride being fulfilled, from driver en route to drop-off. Root of the consistency boundary that includes its legs.",
                  satisfies: ["REQ-RIDE-010", "REQ-RIDE-011"],
                  contains: [{ ref: "rh.rides.RideLeg" }],
                  fields: [
                    { name: "id", type: "RideId" },
                    { name: "requestId", type: "RideRequestId", refKind: "identity of", ref: "rh.rides.RideRequest" },
                    { name: "driverId", type: "DriverId" },
                    { name: "fare", type: "FareEstimate", ref: "rh.rides.FareEstimate", note: "embedded value" },
                    { name: "status", type: "RideStatus", note: "default driverEnRoute" },
                    { name: "startedAt", type: "DateTime", optional: true },
                    { name: "completedAt", type: "DateTime", optional: true },
                  ],
                  operations: [
                    { label: "start the ride", sig: "start(ride): Ride", safe: false, emits: ["rh.rides.ev.RideStarted"] },
                    { label: "complete the ride", sig: "complete(ride, dropoffTime): Ride", safe: false, emits: ["rh.rides.ev.RideCompleted"] },
                    { label: "release the ride for settlement", sig: "release(ride): Ride", safe: false },
                  ],
                  invariants: [{ ref: "rh.rides.inv.fareCoversLegs" }],
                  repository: { ref: "rh.rides.RideRepository" },
                },
                {
                  id: "rh.rides.RideLeg", kind: "entity", name: "RideLeg",
                  description: "One segment of a ride (multi-stop rides have several). Reached only by navigating from the Ride root — no repository of its own.",
                  satisfies: ["REQ-RIDE-011"],
                  partOf: { ref: "rh.rides.Ride" },
                  fields: [
                    { name: "id", type: "RideLegId" },
                    { name: "from", type: "Location", ref: "rh.rides.Location" },
                    { name: "to", type: "Location", ref: "rh.rides.Location" },
                    { name: "distanceKm", type: "Decimal" },
                  ],
                  operations: [],
                },
                {
                  id: "rh.rides.RideRequest", kind: "entity", name: "RideRequest",
                  description: "A rider's intention to travel, from search to match (or cancellation). Identity is the request id; the state machine governs its lifecycle.",
                  satisfies: ["REQ-RIDE-001", "REQ-RIDE-002"],
                  duplicateDetection: "same riderId with an active request (status in searching, matched) and same pickupLocation within 2 minutes",
                  fields: [
                    { name: "id", type: "RideRequestId" },
                    { name: "riderId", type: "RiderId", refKind: "references", ref: "rh.rides.Rider" },
                    { name: "status", type: "RideRequestStatus", note: "default searching" },
                    { name: "pickupLocation", type: "Location", ref: "rh.rides.Location" },
                    { name: "dropoffLocation", type: "Location", ref: "rh.rides.Location" },
                    { name: "committedFare", type: "FareEstimate", ref: "rh.rides.FareEstimate" },
                    { name: "estimatedDriverArrivalTime", type: "DateTime", optional: true },
                    { name: "matchedDriverId", type: "DriverId", optional: true },
                    { name: "matchedAt", type: "DateTime", optional: true },
                    { name: "cancellation", type: "CancellationDetail", ref: "rh.rides.CancellationDetail", optional: true },
                  ],
                  operations: [
                    { label: "request a ride", sig: "request(riderId, pickup, dropoff): RideRequest", safe: false,
                      emits: ["rh.rides.ev.RideRequested", "rh.rides.ev.RideRequestRejected"],
                      preconditions: [{ name: "committed fare still valid", predicate: "committedFare.isExpired() = false", violation: "The quoted fare has expired — request a new quote." }] },
                    { label: "match a driver", sig: "matchDriver(request, driverId, eta): RideRequest", safe: false,
                      emits: ["rh.rides.ev.DriverMatched"],
                      postconditions: [{ name: "driver recorded", predicate: "state_after.matchedDriverId = driverId and state_after.status = matched" }] },
                    { label: "cancel the request", sig: "cancel(request, reason): RideRequest", safe: false, emits: ["rh.rides.ev.RideRequestCancelled"] },
                    { label: "expire the search", sig: "expireSearch(request): RideRequest", safe: false, emits: ["rh.rides.ev.RideRequestCancelled"] },
                  ],
                  invariants: [{ ref: "rh.rides.inv.pickupNotEqualDropoff" }],
                  stateMachines: [{
                    name: "request lifecycle",
                    states: [
                      { name: "searching", initial: true, invariants: ["matchedDriverId is null"] },
                      { name: "matched", invariants: ["matchedDriverId is not null", "matchedAt is not null"] },
                      { name: "cancelled", final: true, invariants: ["cancellation is not null"] },
                    ],
                    transitions: [
                      { from: "searching", to: "matched", operation: "match a driver" },
                      { from: "searching", to: "cancelled", operation: "cancel the request", guard: "no cancellation fee before a match" },
                      { from: "searching", to: "cancelled", operation: "expire the search" },
                      { from: "matched", to: "cancelled", operation: "cancel the request", guard: "cancellation fee applies once matched" },
                    ],
                  }],
                  repository: { ref: "rh.rides.RideRequestRepository" },
                },
                {
                  id: "rh.rides.Rider", kind: "readonly-entity", name: "Rider",
                  description: "Master data owned by the Identity platform. Observable here, never mutated — the projection adapter keeps a local read-model fresh.",
                  satisfies: ["REQ-RIDE-004"],
                  sourcedFrom: "Identity platform (external system)",
                  syncPattern: "asynchronous-projection",
                  projectedBy: { ref: "rh.rides.RiderProjectionAdapter" },
                  fields: [
                    { name: "id", type: "RiderId" },
                    { name: "displayName", type: "String" },
                    { name: "defaultPaymentMethod", type: "PaymentMethodType" },
                    { name: "rating", type: "Decimal" },
                  ],
                  operations: [
                    { label: "check ride eligibility", sig: "isEligibleForRide(rider): Boolean", safe: true },
                  ],
                  repository: { ref: "rh.rides.RiderRepository" },
                },
                {
                  id: "rh.rides.Location", kind: "value", name: "Location",
                  description: "A geographic point with a human-readable label. Transactional constructor rejects coordinates outside the service area.",
                  satisfies: ["REQ-RIDE-002"],
                  fields: [
                    { name: "latitude", type: "Decimal" },
                    { name: "longitude", type: "Decimal" },
                    { name: "label", type: "String", optional: true },
                  ],
                  operations: [
                    { label: "distance to another location", sig: "distanceTo(other: Location): Decimal", safe: true },
                  ],
                  embeddedIn: [{ ref: "rh.rides.RideRequest" }, { ref: "rh.rides.RideLeg" }],
                },
                {
                  id: "rh.rides.FareEstimate", kind: "value", name: "FareEstimate",
                  description: "The fare quoted to the rider, committed at request time. Composes Money; expires to protect against stale surge pricing.",
                  satisfies: ["REQ-RIDE-003"],
                  fields: [
                    { name: "baseFare", type: "Money", ref: "rh.rides.Money" },
                    { name: "surgeMultiplier", type: "Decimal", note: "default 1.0" },
                    { name: "expiresAt", type: "DateTime" },
                  ],
                  operations: [
                    { label: "total fare", sig: "total(): Money", safe: true },
                    { label: "expiry check", sig: "isExpired(): Boolean", safe: true },
                  ],
                  composes: [{ ref: "rh.rides.Money" }],
                  embeddedIn: [{ ref: "rh.rides.RideRequest" }, { ref: "rh.rides.Ride" }],
                },
                {
                  id: "rh.rides.Money", kind: "value", name: "Money",
                  description: "An amount in a currency. Operations return new values; construction fails on negative amounts.",
                  fields: [
                    { name: "amount", type: "BigDecimal" },
                    { name: "currency", type: "Currency", note: "constrained by Currencies", ref: "rh.rides.Currencies" },
                  ],
                  operations: [
                    { label: "add", sig: "add(other: Money): Money", safe: true },
                    { label: "multiply", sig: "multiply(rate: Decimal): Money", safe: true },
                  ],
                  embeddedIn: [{ ref: "rh.rides.FareEstimate" }],
                },
                {
                  id: "rh.rides.CancellationDetail", kind: "value", name: "CancellationDetail",
                  description: "Who cancelled, when, and the fee charged (zero before a match).",
                  fields: [
                    { name: "cancelledBy", type: "CancellationActor", note: "rider · driver · system" },
                    { name: "at", type: "DateTime" },
                    { name: "fee", type: "Money", ref: "rh.rides.Money" },
                  ],
                  embeddedIn: [{ ref: "rh.rides.RideRequest" }],
                },
                {
                  id: "rh.rides.Currencies", kind: "enum", name: "Currencies",
                  description: "Every currency the platform quotes fares in. Values are Currency instances; the ISO code is the reference.",
                  referencesValueType: "Currency (code = ISO 4217 alphabetic code)",
                  values: ["EUR", "USD", "GBP", "CHF"],
                },
                {
                  id: "rh.rides.cmd.RequestARide", kind: "command", name: "RequestARide",
                  description: "The rider's intention to travel. Carries the correlation id for the whole downstream chain of causality.",
                  satisfies: ["REQ-RIDE-001"],
                  fields: [
                    { name: "requestId", type: "RideRequestId", note: "correlation id" },
                    { name: "riderId", type: "RiderId" },
                    { name: "pickup", type: "Location", ref: "rh.rides.Location" },
                    { name: "dropoff", type: "Location", ref: "rh.rides.Location" },
                  ],
                  targets: { ref: "rh.rides.RideRequest" },
                  triggers: "request a ride",
                  produces: [{ ref: "rh.rides.ev.RideRequested" }, { ref: "rh.rides.ev.RideRequestRejected" }],
                },
                {
                  id: "rh.rides.cmd.CancelRide", kind: "command", name: "CancelRide",
                  description: "Rider or system asks to cancel an active request.",
                  satisfies: ["REQ-RIDE-005"],
                  fields: [
                    { name: "requestId", type: "RideRequestId" },
                    { name: "reason", type: "String" },
                  ],
                  targets: { ref: "rh.rides.RideRequest" },
                  triggers: "cancel the request",
                  produces: [{ ref: "rh.rides.ev.RideRequestCancelled" }],
                },
                {
                  id: "rh.rides.cmd.ReleaseRideForSettlement", kind: "command", name: "ReleaseRideForSettlement",
                  description: "Issued by the settlement reaction once payment is confirmed upstream.",
                  fields: [{ name: "rideId", type: "RideId" }],
                  targets: { ref: "rh.rides.Ride" },
                  triggers: "release the ride for settlement",
                  produces: [{ ref: "rh.rides.ev.RideCompleted" }],
                },
                {
                  id: "rh.rides.q.getRideRequest", kind: "query", name: "getRideRequest",
                  description: "Retrieve one request by identity.",
                  queryStyle: "get", carries: "requestId: RideRequestId",
                  readsFrom: { ref: "rh.rides.RideRequestRepository" },
                },
                {
                  id: "rh.rides.q.findActiveRideRequests", kind: "query", name: "findActiveRideRequests",
                  description: "Search requests in searching or matched status, paginated, for the operations dashboard.",
                  queryStyle: "find", carries: "riderId?, status?, page",
                  readsFrom: { ref: "rh.rides.RideRequestRepository" },
                },
                {
                  id: "rh.rides.ev.RideRequested", kind: "event", eventType: "internal", name: "RideRequested",
                  description: "A rider's request entered the search pool.",
                  satisfies: ["REQ-RIDE-001"],
                  fields: [
                    { name: "requestId", type: "RideRequestId" },
                    { name: "riderId", type: "RiderId" },
                    { name: "at", type: "Instant" },
                  ],
                  raisedBy: { ref: "rh.rides.RideRequest", operation: "request a ride" },
                  causedBy: { ref: "rh.rides.cmd.RequestARide" },
                },
                {
                  id: "rh.rides.ev.DriverMatched", kind: "event", eventType: "internal", name: "DriverMatched",
                  description: "A driver accepted the request.",
                  fields: [
                    { name: "requestId", type: "RideRequestId" },
                    { name: "driverId", type: "DriverId" },
                    { name: "eta", type: "DateTime" },
                  ],
                  raisedBy: { ref: "rh.rides.RideRequest", operation: "match a driver" },
                },
                {
                  id: "rh.rides.ev.RideRequestCancelled", kind: "event", eventType: "internal", name: "RideRequestCancelled",
                  description: "The request left the pool before fulfilment.",
                  fields: [
                    { name: "requestId", type: "RideRequestId" },
                    { name: "cancelledBy", type: "CancellationActor" },
                  ],
                  raisedBy: { ref: "rh.rides.RideRequest", operation: "cancel the request" },
                },
                {
                  id: "rh.rides.ev.RideStarted", kind: "event", eventType: "internal", name: "RideStarted",
                  description: "The rider is on board.",
                  fields: [{ name: "rideId", type: "RideId" }, { name: "at", type: "Instant" }],
                  raisedBy: { ref: "rh.rides.Ride", operation: "start the ride" },
                },
                {
                  id: "rh.rides.ev.RideCompleted", kind: "event", eventType: "internal", name: "RideCompleted",
                  description: "Drop-off done; the fare is due.",
                  satisfies: ["REQ-RIDE-010"],
                  fields: [{ name: "rideId", type: "RideId" }, { name: "fareTotal", type: "Money" }],
                  raisedBy: { ref: "rh.rides.Ride", operation: "complete the ride" },
                },
                {
                  id: "rh.rides.ev.RideRequestRejected", kind: "event", eventType: "error", name: "RideRequestRejected",
                  description: "The request could not enter the pool — expired fare, ineligible rider, or duplicate.",
                  satisfies: ["REQ-RIDE-006"],
                  fields: [
                    { name: "requestId", type: "RideRequestId" },
                    { name: "reason", type: "String" },
                  ],
                  raisedBy: { ref: "rh.rides.RideRequest", operation: "request a ride" },
                },
                {
                  id: "rh.rides.ev.PaymentSettled", kind: "event", eventType: "external", name: "PaymentSettled",
                  description: "The payments context confirmed the fare was captured. Consumed through a reaction whose guard checks the ride is still held.",
                  sourcedFrom: "payments (upstream bounded context)",
                  fields: [
                    { name: "paymentIntentId", type: "PaymentIntentId" },
                    { name: "rideId", type: "RideId", note: "correlation id" },
                  ],
                },
                {
                  id: "rh.rides.ev.DriverArrivalDeadlineElapsed", kind: "event", eventType: "temporal", temporalFlavor: "relative",
                  name: "DriverArrivalDeadlineElapsed",
                  description: "The matched driver did not arrive in time. Fires relative to DriverMatched; the guard suppresses it if the driver already arrived.",
                  satisfies: ["REQ-RIDE-020"],
                  reference: { ref: "rh.rides.ev.DriverMatched" },
                  offset: "request.estimatedDriverArrivalTime + 5 minutes",
                  guard: "request.status = matched",
                  recomputation: "re-armed by a reaction listening to DriverEtaRecalculated",
                },
                {
                  id: "rh.rides.rx.releaseRideOnPaymentSettled", kind: "reaction", name: "release ride on payment settled",
                  description: "When payments confirms settlement, release the ride — only if it is still held for settlement.",
                  satisfies: ["REQ-RIDE-010"],
                  triggeredBy: [{ ref: "rh.rides.ev.PaymentSettled" }],
                  guard: "ride.status = heldForSettlement",
                  effects: { ref: "rh.rides.cmd.ReleaseRideForSettlement" },
                },
                {
                  id: "rh.rides.rx.expireSearchOnDeadline", kind: "reaction", name: "expire search on arrival deadline",
                  description: "When the driver-arrival deadline elapses, cancel the request so the rider can rebook.",
                  satisfies: ["REQ-RIDE-020"],
                  triggeredBy: [{ ref: "rh.rides.ev.DriverArrivalDeadlineElapsed" }],
                  guard: "request.status = matched",
                  effects: { ref: "rh.rides.cmd.CancelRide" },
                },
                {
                  id: "rh.rides.RideApplicationService", kind: "application-service", name: "RideApplicationService",
                  description: "Interprets REST requests, opens the use-case transaction, delegates to RideRequest and MatchingService. No domain logic.",
                  operations: [
                    { label: "handle POST /rides", sig: "handleRequestARide(json): 202 Accepted" },
                    { label: "handle DELETE /rides/{id}", sig: "handleCancelRide(id): 204 No Content" },
                  ],
                  delegatesTo: [{ ref: "rh.rides.RideRequest" }, { ref: "rh.matching.MatchingService" }],
                  exposedBy: { ref: "rh.rides.api.RideAPI" },
                },
                {
                  id: "rh.rides.DriverLocationGateway", kind: "infrastructure-service", name: "DriverLocationGateway",
                  description: "Adapter over the fleet telemetry stream, speaking this context's language. Fulfils the DriverLocationSPI contract.",
                  operations: [
                    { label: "nearest available drivers", sig: "nearestAvailable(location, radius): [DriverId]" },
                  ],
                  describedBy: { ref: "rh.rides.spi.DriverLocationSPI" },
                  usedBy: [{ ref: "rh.matching.MatchingService" }],
                },
                {
                  id: "rh.rides.RiderProjectionAdapter", kind: "infrastructure-service", name: "RiderProjectionAdapter",
                  description: "Anti-corruption layer: subscribes to Identity-platform events, translates them, and refreshes the Rider read-model behind its repository SPI. The domain never sees the write.",
                  operations: [{ label: "refresh rider read-model", sig: "onIdentityEvent(evt): void" }],
                  describedBy: { ref: "rh.rides.spi.RiderRepositorySPI" },
                  usedBy: [],
                },
                {
                  id: "rh.rides.RideRequestRepository", kind: "repository", name: "RideRequestRepository",
                  description: "Collection-like access to ride requests, keyed by identity. findByRider deduced from the operations dashboard use case.",
                  derivedFrom: { ref: "rh.rides.RideRequest" },
                  operations: ["store", "getById", "remove", "search", "findByRiderId", "findByStatus"],
                  describedBy: { ref: "rh.rides.spi.RideRequestRepositorySPI" },
                  readBy: [{ ref: "rh.rides.q.getRideRequest" }, { ref: "rh.rides.q.findActiveRideRequests" }],
                },
                {
                  id: "rh.rides.RideRepository", kind: "repository", name: "RideRepository",
                  description: "Persistence for the Ride aggregate root. RideLeg is reached only through the root.",
                  derivedFrom: { ref: "rh.rides.Ride" },
                  operations: ["store", "getById", "remove", "search"],
                },
                {
                  id: "rh.rides.RiderRepository", kind: "repository", name: "RiderRepository", readOnly: true,
                  description: "Read-only surface over the Rider projection: getById, findByField, search — never store or remove.",
                  derivedFrom: { ref: "rh.rides.Rider" },
                  operations: ["getById", "findByDisplayName", "search"],
                  describedBy: { ref: "rh.rides.spi.RiderRepositorySPI" },
                },
                {
                  id: "rh.rides.api.RideAPI", kind: "interface", role: "API", name: "RideAPI",
                  description: "The module's public surface: the ride use cases consumers may call. Selects operations already owned by the application service.",
                  exposes: ["handleRequestARide", "handleCancelRide", "getRideRequest", "findActiveRideRequests"],
                  exposesFrom: [{ ref: "rh.rides.RideApplicationService" }],
                },
                {
                  id: "rh.rides.spi.RideRequestRepositorySPI", kind: "interface", role: "SPI", name: "RideRequestRepositorySPI",
                  description: "The persistence port the domain depends on; a database adapter implements it.",
                  exposes: ["store", "getById", "remove", "search", "findByRiderId", "findByStatus"],
                  describes: { ref: "rh.rides.RideRequestRepository" },
                },
                {
                  id: "rh.rides.spi.RiderRepositorySPI", kind: "interface", role: "SPI", name: "RiderRepositorySPI",
                  description: "Read-only port over the rider projection.",
                  exposes: ["getById", "findByDisplayName", "search"],
                  describes: { ref: "rh.rides.RiderRepository" },
                },
                {
                  id: "rh.rides.spi.DriverLocationSPI", kind: "interface", role: "SPI", name: "DriverLocationSPI",
                  description: "What the domain needs from fleet telemetry, in its own words: where are the nearest available drivers.",
                  exposes: ["nearestAvailable"],
                  describes: { ref: "rh.rides.DriverLocationGateway" },
                  usedBy: [{ ref: "rh.matching.MatchingService" }],
                },
                {
                  id: "rh.rides.inv.pickupNotEqualDropoff", kind: "invariant", name: "pickup differs from dropoff",
                  description: "A request whose pickup and dropoff are the same location is meaningless.",
                  satisfies: ["REQ-RIDE-002"],
                  scopedTo: { ref: "rh.rides.RideRequest" },
                  predicate: "pickupLocation ≠ dropoffLocation",
                  enforcement: "rejection",
                },
                {
                  id: "rh.rides.inv.fareCoversLegs", kind: "invariant", name: "fare covers all legs",
                  description: "The committed fare total must equal the sum of the fares of the ride's legs.",
                  satisfies: ["REQ-RIDE-011"],
                  scopedTo: { ref: "rh.rides.Ride" },
                  predicate: "fare.total() = sum(legs.fare)",
                  enforcement: "rejection",
                },
              ],
            },
            {
              id: "rh.matching", name: "matching",
              description: "Pairs searching requests with available drivers. Pure domain logic over the driver-location SPI.",
              elements: [
                {
                  id: "rh.matching.MatchingService", kind: "domain-service", name: "MatchingService",
                  description: "Spans RideRequest and driver availability — ownership by either would be arbitrary. Picks the best driver and drives the match.",
                  satisfies: ["REQ-RIDE-007"],
                  operations: [
                    { label: "match request to best driver", sig: "match(request: RideRequest): RideRequest", safe: false, emits: ["rh.rides.ev.DriverMatched"] },
                  ],
                  calls: [{ ref: "rh.rides.DriverLocationGateway" }],
                },
              ],
            },
            {
              id: "rh.pricing", name: "pricing",
              description: "Quotes fares: base rates, surge multipliers, promotions.",
              elements: [
                {
                  id: "rh.pricing.PricingService", kind: "domain-service", name: "PricingService",
                  description: "Computes a committed FareEstimate for a pickup/dropoff pair at the current surge level.",
                  satisfies: ["REQ-RIDE-003"],
                  operations: [
                    { label: "quote a fare", sig: "quote(pickup, dropoff): FareEstimate", safe: true },
                    { label: "current surge for a zone", sig: "surgeFor(zone): Decimal", safe: true },
                  ],
                },
                {
                  id: "rh.pricing.ev.SurgeRecalculationDue", kind: "event", eventType: "temporal", temporalFlavor: "recurring",
                  name: "SurgeRecalculationDue",
                  description: "Standing commitment: recompute surge multipliers for every zone.",
                  schedule: "every 2 minutes",
                  guard: "true — always fires on schedule",
                },
              ],
            },
          ],
        },
        {
          id: "payments",
          name: "Payments",
          shortname: "pay",
          description: "Captures and settles fares. Upstream of ride-hailing; exposes a stable protocol to every consumer.",
          relations: [
            { with: "ride-hailing", position: "upstream", pattern: "OHS",
              note: "Publishes a versioned settlement contract; never accommodates any single consumer's model." },
          ],
          modules: [
            {
              id: "pay.settlement", name: "settlement",
              description: "Payment intents, capture, and the fare-settlement agreement with ride-hailing.",
              elements: [
                {
                  id: "pay.settlement.PaymentIntent", kind: "aggregate", name: "PaymentIntent",
                  description: "The commitment to collect a fare. Root of the settlement consistency boundary.",
                  satisfies: ["REQ-PAY-001"],
                  contains: [],
                  fields: [
                    { name: "id", type: "PaymentIntentId" },
                    { name: "rideId", type: "RideId", note: "correlation id" },
                    { name: "amount", type: "Money" },
                    { name: "status", type: "PaymentStatus", note: "default pending" },
                  ],
                  operations: [
                    { label: "capture the payment", sig: "capture(intent): PaymentIntent", safe: false, emits: ["pay.settlement.ev.PaymentSettled", "pay.settlement.ev.PaymentFailed"] },
                  ],
                  repository: { ref: "pay.settlement.PaymentIntentRepository" },
                },
                {
                  id: "pay.settlement.cmd.SettlePayment", kind: "command", name: "SettlePayment",
                  description: "Collect the fare for a completed ride.",
                  satisfies: ["REQ-PAY-001"],
                  fields: [{ name: "paymentIntentId", type: "PaymentIntentId" }],
                  targets: { ref: "pay.settlement.PaymentIntent" },
                  triggers: "capture the payment",
                  produces: [{ ref: "pay.settlement.ev.PaymentSettled" }, { ref: "pay.settlement.ev.PaymentFailed" }],
                },
                {
                  id: "pay.settlement.ev.PaymentSettled", kind: "event", eventType: "internal", name: "PaymentSettled",
                  description: "The fare was captured. Published through the OHS contract; ride-hailing consumes it as an external event.",
                  fields: [{ name: "paymentIntentId", type: "PaymentIntentId" }, { name: "rideId", type: "RideId" }],
                  raisedBy: { ref: "pay.settlement.PaymentIntent", operation: "capture the payment" },
                },
                {
                  id: "pay.settlement.ev.PaymentFailed", kind: "event", eventType: "error", name: "PaymentFailed",
                  description: "Capture failed — card declined or gateway timeout.",
                  fields: [{ name: "paymentIntentId", type: "PaymentIntentId" }, { name: "reason", type: "String" }],
                  raisedBy: { ref: "pay.settlement.PaymentIntent", operation: "capture the payment" },
                },
                {
                  id: "pay.settlement.PaymentGateway", kind: "infrastructure-service", name: "PaymentGateway",
                  description: "Adapter over the card-processing provider, in the settlement module's language.",
                  satisfies: ["REQ-NFR-001"],
                  operations: [{ label: "charge a card", sig: "charge(token, amount): ChargeResult" }],
                  describedBy: { ref: "pay.settlement.spi.PaymentGatewaySPI" },
                  usedBy: [{ ref: "pay.settlement.PaymentIntent" }],
                },
                {
                  id: "pay.settlement.spi.PaymentGatewaySPI", kind: "interface", role: "SPI", name: "PaymentGatewaySPI",
                  description: "What settlement needs from any card processor.",
                  exposes: ["charge"],
                  describes: { ref: "pay.settlement.PaymentGateway" },
                },
                {
                  id: "pay.settlement.PaymentIntentRepository", kind: "repository", name: "PaymentIntentRepository",
                  description: "Persistence for payment intents.",
                  derivedFrom: { ref: "pay.settlement.PaymentIntent" },
                  operations: ["store", "getById", "remove", "search", "findByRideId"],
                },
                {
                  id: "pay.settlement.agr.FareSettlement", kind: "agreement", name: "fare settlement agreement",
                  description: "Every completed ride ends up with exactly one settled payment of the committed fare. No single transaction can verify this — Ride and PaymentIntent live in different contexts.",
                  satisfies: ["REQ-PAY-005"],
                  arity: "bilateral",
                  involves: [{ ref: "rh.rides.Ride" }, { ref: "pay.settlement.PaymentIntent" }],
                  predicate: "for every Ride with status = completed there exists exactly one PaymentIntent with status = settled and amount = ride.fare.total()",
                  inconsistencyWindow: "up to 15 minutes between ride completion and settlement confirmation",
                  maintainedBy: { ref: "pay.settlement.rec.fareSettlementReconciliation" },
                },
                {
                  id: "pay.settlement.rec.fareSettlementReconciliation", kind: "reconciliation", name: "fare settlement reconciliation",
                  description: "Detects completed rides without a settled payment and drives them back to consistency. Orchestrated as a settlement saga.",
                  satisfies: ["REQ-PAY-005"],
                  maintains: { ref: "pay.settlement.agr.FareSettlement" },
                  trigger: "schedule — every 15 minutes",
                  detection: "query-based: compare completed rides against settled intents over the last 24h",
                  coordination: "orchestrated (settlement saga)",
                  compensation: [{ ref: "pay.settlement.cmd.SettlePayment" }],
                  escalation: [
                    { condition: "capture failed", action: "retry", maxAttempts: 3, note: "exponential backoff" },
                    { condition: "retries exhausted", action: "alternative compensation", note: "charge the rider's secondary payment method" },
                    { condition: "alternative failed", action: "manual intervention", note: "work item for the payments-ops team, carrying full failure context" },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: "driver-fleet",
          name: "Driver Fleet",
          shortname: "fleet",
          description: "Driver onboarding, availability, and telemetry. Supplier to ride-hailing under a Customer/Supplier relationship.",
          relations: [
            { with: "ride-hailing", position: "upstream", pattern: "Customer/Supplier",
              note: "Ride-hailing's needs shape the availability interface; changes are negotiated before deployment." },
          ],
          modules: [
            {
              id: "fleet.availability", name: "availability",
              description: "Which drivers are online and where.",
              elements: [
                {
                  id: "fleet.availability.Driver", kind: "entity", name: "Driver",
                  description: "A driver's availability lifecycle. Owned here; ride-hailing sees only projections.",
                  satisfies: ["REQ-FLEET-001"],
                  fields: [
                    { name: "id", type: "DriverId" },
                    { name: "status", type: "DriverStatus", note: "default offline" },
                    { name: "lastKnownLocation", type: "GeoPoint", optional: true },
                  ],
                  operations: [
                    { label: "go online", sig: "goOnline(driver): Driver", safe: false, emits: ["fleet.availability.ev.DriverWentOnline"] },
                    { label: "go offline", sig: "goOffline(driver): Driver", safe: false },
                  ],
                  stateMachines: [{
                    name: "availability",
                    states: [
                      { name: "offline", initial: true },
                      { name: "online" },
                      { name: "onRide" },
                    ],
                    transitions: [
                      { from: "offline", to: "online", operation: "go online" },
                      { from: "online", to: "offline", operation: "go offline" },
                    ],
                  }],
                  repository: { ref: "fleet.availability.DriverRepository" },
                },
                {
                  id: "fleet.availability.ev.DriverWentOnline", kind: "event", eventType: "internal", name: "DriverWentOnline",
                  description: "A driver joined the available pool.",
                  fields: [{ name: "driverId", type: "DriverId" }, { name: "at", type: "Instant" }],
                  raisedBy: { ref: "fleet.availability.Driver", operation: "go online" },
                },
                {
                  id: "fleet.availability.DriverRepository", kind: "repository", name: "DriverRepository",
                  description: "Persistence for drivers.",
                  derivedFrom: { ref: "fleet.availability.Driver" },
                  operations: ["store", "getById", "remove", "search", "findByStatus"],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "acme-retail",
      name: "Acme Retail",
      description: "The group's e-commerce arm. One context modeled so far.",
      requirementsSource: "specy/acme-retail.sysreq",
      contexts: [
        {
          id: "ordering",
          name: "Ordering",
          shortname: "ord",
          description: "Order capture and fulfilment kickoff.",
          relations: [],
          modules: [
            {
              id: "ord.orders", name: "orders",
              description: "The order lifecycle from placement to handoff.",
              elements: [
                {
                  id: "ord.orders.Order", kind: "entity", name: "Order",
                  description: "A customer's confirmed purchase.",
                  satisfies: ["REQ-ORD-002"],
                  fields: [
                    { name: "id", type: "OrderId" },
                    { name: "customerId", type: "CustomerId" },
                    { name: "lines", type: "[LineItem]" },
                    { name: "status", type: "OrderStatus", note: "default placed" },
                  ],
                  operations: [
                    { label: "place the order", sig: "place(customerId, lines): Order", safe: false, emits: ["ord.orders.ev.OrderPlaced"] },
                  ],
                  invariants: [{ ref: "ord.orders.inv.positiveQuantity" }],
                  repository: { ref: "ord.orders.OrderRepository" },
                },
                {
                  id: "ord.orders.cmd.PlaceOrder", kind: "command", name: "PlaceOrder",
                  description: "The customer's intention to buy.",
                  satisfies: ["REQ-ORD-002"],
                  fields: [
                    { name: "orderId", type: "OrderId" },
                    { name: "customerId", type: "CustomerId" },
                    { name: "lines", type: "[LineItem]" },
                  ],
                  targets: { ref: "ord.orders.Order" },
                  triggers: "place the order",
                  produces: [{ ref: "ord.orders.ev.OrderPlaced" }],
                },
                {
                  id: "ord.orders.ev.OrderPlaced", kind: "event", eventType: "internal", name: "OrderPlaced",
                  description: "The order entered the fulfilment pipeline.",
                  fields: [{ name: "orderId", type: "OrderId" }, { name: "total", type: "Money" }],
                  raisedBy: { ref: "ord.orders.Order", operation: "place the order" },
                  causedBy: { ref: "ord.orders.cmd.PlaceOrder" },
                },
                {
                  id: "ord.orders.OrderRepository", kind: "repository", name: "OrderRepository",
                  description: "Persistence for orders.",
                  derivedFrom: { ref: "ord.orders.Order" },
                  operations: ["store", "getById", "remove", "search", "findByCustomerId"],
                },
                {
                  id: "ord.orders.inv.positiveQuantity", kind: "invariant", name: "positive line quantity",
                  description: "Every line item's quantity is strictly positive.",
                  satisfies: ["REQ-ORD-001"],
                  scopedTo: { ref: "ord.orders.Order" },
                  predicate: "all lines: quantity > 0",
                  enforcement: "rejection",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
